[package]
name = "evm"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
utils = { path = "../utils" }
contracts = { path = "../contracts" }
openzeppelin = { path = "../openzeppelin" }
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", branch = "g2" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }
snforge_utils = { path = "../snforge_utils" }
assert_macros = "2.8.2"

[tool]
fmt.workspace = true

[scripts]
test = "snforge test --max-n-steps 4294967295"
test-profiling = "snforge test --max-n-steps 4294967295 --build-profile"

# required to avoid:
# error: Invalid order of type declarations for serialization.
# tracking: https://github.com/starkware-libs/cairo/issues/6607
[cairo]
sierra-replace-ids = false
